# enableGlobalCache: true
nodeLinker: node-modules
# pnpMode: Loose

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'linux'
  cpu:
    - 'current'
    - 'x86'
    - 'ia32'

packageExtensions:
  'stylelint-config-standard-scss@*':
    peerDependencies:
      postcss: '^8.3.3'
      stylelint-config-recommended-scss: '^8.3.3'
  'stylelint-config-recommended-scss@*':
    peerDependencies:
      postcss: '^8.3.3'
  '@netlify/build@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '>=2.7'
  'netlify-cli@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '>=2.7'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '>=2.7'
  'personal-portfolio@*':
    peerDependencies:
      stylelint: '^13.0.0'
      postcss: '*'
  'stylelint-config-sass-guidelines@*':
    peerDependencies:
      stylelint: '^8.0.0'
