# enableGlobalCache: true
# nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  'stylelint-config-standard-scss@*':
    peerDependencies:
      postcss: '*'
  'stylelint-config-recommended-scss@*':
    peerDependencies:
      postcss: '*'
  '@netlify/build@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  'netlify-cli@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '*'
