nodeLinker: node-modules

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '>=2.7'
  '@netlify/build@*':
    peerDependencies:
      '@types/node': '>=2.7'
      typescript: '*'
  netlify-cli@*:
    peerDependencies:
      '@types/node': '>=2.7'
      typescript: '*'
  personal-portfolio@*:
    peerDependencies:
      stylelint: ^13.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  cpu:
    - current
    - x86
    - ia32
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.1.1.cjs
