import NextHead from 'next/head'

// import { DefaultSeo } from 'next-seo'
// import config from '@config/seo.json'

const Head = function () {
  return (
    <NextHead>
      <title>Shaun Fitzgibbon - Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />;
      <link rel="icon" href="/favicon.ico" />
      <link sizes="180x180" href="/apple-touch-icon.png" />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/favicon-16x16.png"
      />
      <link rel="manifest" href="/site.webmanifest" />
    </NextHead>
  )
}

export default Head
