import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import styles from '@assets/styles/Home.module.css'
import { projects } from '../data/data'
import { Card } from '@components/ui'

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      projects,
    },
  }
}

const Home: NextPage = ({ projects }: any) => {
  return (
    <>
      <Head>
        <title>Shaun Fitzgibbon - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>

      <section className={styles['hero-section']}>
        <h1 className={styles.title}>
          Hi, I{'&apos'}m <a href="https://nextjs.org">Shaun Fitzgibbon</a>{' '}
          <br /> I{'&apos'}m a web developer
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button>About me</button>
      </section>

      <section id="about-section" className={styles['about-section']}>
        <h2>About Me</h2>
      </section>

      <section id="projects-section" className={styles['projects-section']}>
        <h2>My Projects</h2>
        <div className={styles.grid}>
          {projects.map((project: any) => (
            <Card key={project.id} project={project} />
          ))}
        </div>
      </section>

      <section id="contact-section" className={styles['contact-section']}>
        <h2>Hit me up</h2>
      </section>
    </>
  )
}

export default Home
