name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing node dependencies
        run: yarn --frozen-lockfile

      - name: Performing React tests if any defined
        run: yarn test

      - name: Running ESLint Linter
        run: yarn eslint

      - name: Save Code Linting Report JSON
        run: yarn eslint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./reports/eslint_report.json"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: ./reports/eslint_report.json

      - name: Running Stylelint
        run: yarn stylelint

      - name: Running Prettier Code Formatter
        run: yarn prettier

      - name: Performing React build
        run: yarn build
