name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing node dependencies
        run: yarn --frozen-lockfile

      - name: Performing React tests if any defined
        run: yarn test
        env:
          CI: true # so that the test prompt doesn't show up

      # - name: Running ESLint Linter
      #   run: yarn eslint
      #   working-directory: ./frontend
      #   env:
      #     CI: false

      - name: Save Code Linting Report JSON
        # npm script for ESLint
        # eslint --output-file eslint_report.json --format json src
        # See https://eslint.org/docs/user-guide/command-line-interface#options
        run: yarn run eslint:report
        # Continue to the next step even if this fails
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: './frontend/eslint_report.json'

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: ./frontend/eslint_report.json

      - name: Performing React build
        run: yarn build --if-present
        env:
          CI: false # causes warnings to become errors, and there are tons of pa11y errors to fix

      - name: Upload build files
        uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: frontend/build/
