# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installing node dependencies
      run: yarn ci
      working-directory: ./frontend
      
    - name: Performing React build 
      run: yarn build --if-present
      working-directory: ./frontend
      env:
        CI: false # causes warnings to become errors, and there are tons of pa11y errors to fix
    
    - name: Performing React tests if any defined 
      run: yarn test
      working-directory: ./frontend
      env:
        CI: true # so that the test prompt doesn't show up
